substitutions:
  name: esp01-ikea-vindriktning
  wifi_ap_password: ""

esphome:
  name: ${name}
  name_add_mac_suffix: true
  project:
    name: nepozs.esphome-projects-vindriktning
    version: "vindriktning 0.5"

esp8266:
  board: esp01_1m

wifi:
  ap:
    password: ${wifi_ap_password}
  power_save_mode: none
  output_power: 17

api:
## 1st stage modifying project to be ready for Hi-Link HLK-LD2410 (hardware logger makes no sense when ESP-01 is soldered in some device)
## logger over serial must be switched off when using hardware serial for other purpose - 
logger:
  baud_rate: 0
  esp8266_store_log_strings_in_flash: false
ota:
## improv serial impossible when ESP-01 modlue is soldered inside Vindriktning device, configure is possible using captive portal
#improv_serial:
captive_portal:

web_server:
  port: 80
  local: true
  
dashboard_import:
  package_import_url: github://nepozs/esphome-projects/esp01-ikea-vindriktning.yaml@master

# change to hardware UART
uart:
  rx_pin: GPIO3
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: "Particulate Matter 2.5µm Concentration"
      filters:
        - median:
            window_size: 7
            send_every: 4
            send_first_at: 3

  - platform: uptime
    name: "${name} Uptime"
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "h"
  - platform: adc
    pin: VCC
    name: "${name} VCC Voltage"

switch:
  - platform: restart
    name: "${name} Restart"
  - platform: factory_reset
    name: "${name} Restart with Factory Default Settings"
